[package]
name = "cross-visa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
visa = "=0.1.0"
serde_json = "1.0.1"
serde = { version = "1.0.202", features = ["derive"] }
dlopen = "=0.1.8"