name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  core_tests:
    runs-on: windows-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    
    - name: Install NI Package Manager
      run: |
        # Install NI Package Manager silently
        Start-Process -FilePath "C:\NI-Package-Manager.exe" -ArgumentList "/qb /AcceptLicenses yes" -Wait

    - name: Install NI-VISA via NI Package Manager
      run: |
        # Use NI Package Manager to install NI-VISA silently
        # Note: Adjust command to include necessary flags for your installation
        "C:\Program Files\National Instruments\NI Package Manager\nipkg.exe" install ni-visa --accept-eula --quiet --include-recommended --prevent-reboot --confirm

    - name: Run core tests
      run: cargo test --test core_tests